TEXTOS = {
    "pt": {
        "select_lang": "🇧🇷 Português selecionado.",
        "select_cat": "Selecione a Categoria...",
        "modal_title": "Calcular: {}",
        "label_skill": "Seu Skill de Crafting",
        "label_qtd": "Quantidade desejada?",
        "btn_craft": "🔨 Crafting", "btn_skill": "⚔️ Skills", "btn_alch": "🧪 Alchemy", "btn_rashid": "🕌 Rashid", "btn_tools": "🛠️ Extras", "btn_wiki": "📖 Wiki",
        "wiki_monster": "🐲 Monstro", "wiki_item": "🛡️ Vendas de Item", "wiki_label": "Nome (Inglês)", "wiki_ph": "Ex: Dragon ou Fire Sword",
        "wiki_error": "❌ Dados não encontrados para '{}'.",
        "tools_select": "🛠️ Menu de Ferramentas", "btn_party": "🤝 Party", "btn_ss": "💾 Server Save", "btn_mining": "⛏️ Mining",
        "mining_title": "⛏️ Mineração", "mining_skill_label": "Seu Skill de Mining", "mining_pick_ph": "Escolha a Picareta...",
        "mining_res_break": "💥 Chance de Quebrar:", "mining_res_min": "💎 Minerais (Comuns):", "mining_res_frag": "🔥 Fragmentos (Raros):",
        "ss_msg": "⏳ Faltam **{}** para o Server Save (05:00 BRT).",
        "cats": { "relics": "💎 Relíquias", "runes": "✨ Runas", "tools": "⛏️ Ferramentas", "fishing": "🎣 Pesca", "ammo": "📦 Munições" },
        "rashid_title": "🕌 Rashid está em: {}", "rashid_desc": "📍 {}", "rashid_map": "🗺️ Ver no Mapa",
        "alch_gold": "💰 Gold Converter", "alch_skill_label": "Seu Skill de Alchemy", "alch_gold_label": "Total de Gold (GP)?", "alch_needs": "📦 Você precisa comprar:", "alch_conv_name": "Gold Converters"
    },
    "en": {
        "select_lang": "🇺🇸 English selected.",
        "select_cat": "Select Category...",
        "modal_title": "Calculate: {}",
        "label_skill": "Your Crafting Skill",
        "label_qtd": "Quantity desired?",
        "btn_craft": "🔨 Crafting", "btn_skill": "⚔️ Skills", "btn_alch": "🧪 Alchemy", "btn_rashid": "🕌 Rashid", "btn_tools": "🛠️ Extras", "btn_wiki": "📖 Wiki",
        "wiki_monster": "🐲 Monster", "wiki_item": "🛡️ Item Sales", "wiki_label": "Search Name (English)", "wiki_ph": "Ex: Dragon",
        "wiki_error": "❌ Not found for '{}'.",
        "tools_select": "🛠️ Tools Menu", "btn_party": "🤝 Party", "btn_ss": "💾 Server Save", "btn_mining": "⛏️ Mining",
        "mining_title": "⛏️ Mining Calculator", "mining_skill_label": "Your Mining Skill", "mining_pick_ph": "Select Pickaxe...",
        "mining_res_break": "💥 Break Chance:", "mining_res_min": "💎 Minerals (Common):", "mining_res_frag": "🔥 Fragments (Rare):",
        "ss_msg": "⏳ **{}** remaining until Server Save (05:00 BRT).",
        "cats": { "relics": "💎 Relics", "runes": "✨ Runes", "tools": "⛏️ Tools", "fishing": "🎣 Fishing", "ammo": "📦 Ammunition" },
        "rashid_title": "🕌 Rashid is at: {}", "rashid_desc": "📍 {}", "rashid_map": "🗺️ View on Map",
        "alch_gold": "💰 Gold Convert", "alch_skill_label": "Your Alchemy Skill", "alch_gold_label": "Total Gold Amount (GP)?", "alch_needs": "📦 You need to buy:", "alch_conv_name": "Gold Converters"
    },
    "pl": {
        "select_lang": "🇵🇱 Język polski wybrany.",
        "select_cat": "Wybierz Kategorię...",
        "modal_title": "Oblicz: {}",
        "label_skill": "Twój Skill Craftingu",
        "label_qtd": "Oczekiwana ilość?",
        "btn_craft": "🔨 Crafting", "btn_skill": "⚔️ Skills", "btn_alch": "🧪 Alchemia", "btn_rashid": "🕌 Rashid", "btn_tools": "🛠️ Narzędzia", "btn_wiki": "📖 Wiki",
        "wiki_monster": "🐲 Potwór", "wiki_item": "🛡️ Przedmiot", "wiki_label": "Szukaj nazwy (Angielski)", "wiki_ph": "Np: Dragon",
        "wiki_error": "❌ Nie znaleziono '{}'.",
        "tools_select": "🛠️ Narzędzia", "btn_party": "🤝 Party", "btn_ss": "💾 Server Save", "btn_mining": "⛏️ Górnictwo",
        "mining_title": "⛏️ Kalkulator Górniczy", "mining_skill_label": "Twój Skill Górnictwa", "mining_pick_ph": "Wybierz Kilof...",
        "mining_res_break": "💥 Szansa na rozbicie:", "mining_res_min": "💎 Minerały (Zwykłe):", "mining_res_frag": "🔥 Fragmenty (Rzadkie):",
        "ss_msg": "⏳ **{}** do zapisu serwera (05:00 BRT).",
        "cats": { "relics": "💎 Relikty", "runes": "✨ Runy", "tools": "⛏️ Narzędzia", "fishing": "🎣 Wędkarstwo", "ammo": "📦 Amunicja" },
        "rashid_title": "🕌 Rashid jest w: {}", "rashid_desc": "📍 {}", "rashid_map": "🗺️ Zobacz na mapie",
        "alch_gold": "💰 Konwersja Złota", "alch_skill_label": "Twój Skill Alchemii", "alch_gold_label": "Całkowita ilość złota (GP)?", "alch_needs": "📦 Musisz kupić:", "alch_conv_name": "Gold Converters"
    }
}
