TEXTOS = {
    "pt": {
        "select_lang": "🇧🇷 Português selecionado.", "select_cat": "Selecione a Categoria...",
        "ask_category": "📂 O que você deseja craftar?", "ask_item": "Qual item de **{}**?",
        "modal_title": "Calcular: {}", "label_skill": "Seu Skill de Crafting",
        "placeholder_skill": "Receita 1un: {}", "label_qtd": "Quantidade desejada?", "placeholder_qtd": "Ex: 10",
        "label_price": "Preço {} (Usa {})", "placeholder_price": "Perde na falha: {}",
        "yes": "Sim", "no": "Não", "result_title": "⚒️ Resultado: {}x {}", "chance": "🎯 Chance Sucesso",
        "cost": "💰 Custo Total", "list": "📦 Lista de Compras", "footer": "Calculado para {} | Fuso Manaus",
        "btn_craft": "🔨 Crafting", "btn_skill": "⚔️ Skills", "btn_alch": "🧪 Alchemy", "btn_rashid": "🕌 Rashid", "btn_tools": "🛠️ Extras", "btn_wiki": "📖 Wiki", "btn_donate": "💰 Donate",
        "donate_title": "☕ Apoie o Projeto", "donate_desc": "Ajude a manter o bot online!",
        "wiki_monster": "🐲 Monstro", "wiki_label": "Nome (Inglês)", "wiki_ph": "Ex: Dragon", "wiki_error": "❌ Não encontrado: '{}'",
        "wiki_select": "📖 Pesquisar",
        "mining_title": "⛏️ Mineração", "mining_skill_label": "Skill", "mining_res_break": "Quebrar", "mining_res_min": "Minerais", "mining_res_frag": "Fragmentos",
        "tools_select": "🛠️ Ferramentas", "btn_party": "🤝 Party", "btn_ss": "💾 Server Save", "btn_mining": "⛏️ Mining",
        "party_title": "Party Share", "party_label": "Level", "party_res": "Level {}:",
        "ss_msg": "⏳ Faltam **{}** para o SS.", "ss_title": "Server Save",
        "cats": { "relics": "💎 Relíquias", "runes": "✨ Runas", "tools": "⛏️ Ferramentas", "fishing": "🎣 Pesca", "ammo": "📦 Munições" },
        "rashid_title": "🕌 Rashid está em: {}", "rashid_desc": "📍 {}", "rashid_map": "🗺️ Ver no Mapa", "rashid_error": "Erro.",
        "alch_select": "⚗️ Menu", "alch_gold": "💰 Gold Converter", "alch_skill_label": "Skill", "alch_needs": "Precisa de:", "alch_conv_name": "Converters", "alch_gold_label": "Total Gold", "alch_gold_ph": "Ex: 10k", "alch_res_gold": "Gold", "alch_chance": "Chance", "cost": "Custo",
        "time_est": "⏳ Tempo"
    },
    "en": {
        "select_lang": "🇺🇸 English selected.", "select_cat": "Select Category...",
        "ask_category": "📂 What to craft?", "ask_item": "Which item from **{}**?",
        "modal_title": "Calculate: {}", "label_skill": "Crafting Skill",
        "placeholder_skill": "Recipe 1x: {}", "label_qtd": "Quantity desired?", "placeholder_qtd": "Ex: 10",
        "label_price": "Price {} (Uses {})", "placeholder_price": "Lost on fail: {}",
        "yes": "Yes", "no": "No", "result_title": "⚒️ Result: {}x {}", "chance": "🎯 Success Chance",
        "cost": "💰 Total Cost", "list": "📦 Shopping List", "footer": "Calc",
        "btn_craft": "🔨 Crafting", "btn_skill": "⚔️ Skills", "btn_alch": "🧪 Alchemy", "btn_rashid": "🕌 Rashid", "btn_tools": "🛠️ Extras", "btn_wiki": "📖 Wiki", "btn_donate": "💰 Donate",
        "donate_title": "☕ Support Us", "donate_desc": "Help keep the bot running!",
        "wiki_monster": "🐲 Monster", "wiki_label": "Name (English)", "wiki_ph": "Ex: Dragon", "wiki_error": "❌ Not found: '{}'",
        "wiki_select": "📖 Search",
        "mining_title": "⛏️ Mining", "mining_skill_label": "Skill", "mining_res_break": "Break", "mining_res_min": "Minerals", "mining_res_frag": "Fragments",
        "tools_select": "🛠️ Tools", "btn_party": "🤝 Party", "btn_ss": "💾 Server Save", "btn_mining": "⛏️ Mining",
        "party_title": "Party Share", "party_label": "Level", "party_res": "Level {}:",
        "ss_msg": "⏳ **{}** until SS.", "ss_title": "Server Save",
        "cats": { "relics": "💎 Relics", "runes": "✨ Runas", "tools": "⛏️ Tools", "fishing": "🎣 Fishing", "ammo": "📦 Ammo" },
        "rashid_title": "🕌 Rashid is at: {}", "rashid_desc": "📍 {}", "rashid_map": "🗺️ Map", "rashid_error": "Error.",
        "alch_select": "⚗️ Menu", "alch_gold": "💰 Gold Convert", "alch_skill_label": "Skill", "alch_needs": "Need:", "alch_conv_name": "Converters", "alch_gold_label": "Total Gold", "alch_gold_ph": "Ex: 10k", "alch_res_gold": "Gold", "alch_chance": "Chance", "cost": "Cost",
        "time_est": "⏳ Time"
    },
    "pl": {
        "select_lang": "🇵🇱 Język polski wybrany.", "select_cat": "Wybierz Kategorię...",
        "ask_category": "📂 Co stworzyć?", "ask_item": "Który przedmiot **{}**?",
        "modal_title": "Oblicz: {}", "label_skill": "Skill Craftingu",
        "placeholder_skill": "Przepis 1szt: {}", "label_qtd": "Ilość", "placeholder_qtd": "Np: 10",
        "label_price": "Cena {} (Używa {})", "placeholder_price": "Strata przy błędzie: {}",
        "yes": "Tak", "no": "Nie", "result_title": "⚒️ Wynik: {}x {}", "chance": "🎯 Szansa",
        "cost": "💰 Koszt", "list": "📦 Lista", "footer": "Calc",
        "btn_craft": "🔨 Crafting", "btn_skill": "⚔️ Skills", "btn_alch": "🧪 Alchemia", "btn_rashid": "🕌 Rashid", "btn_tools": "🛠️ Narzędzia", "btn_wiki": "📖 Wiki", "btn_donate": "💰 Donate",
        "donate_title": "☕ Wesprzyj nas", "donate_desc": "Pomóż utrzymać bota!",
        "wiki_monster": "🐲 Potwór", "wiki_label": "Nazwa (Angielski)", "wiki_ph": "Np: Dragon", "wiki_error": "❌ Nie znaleziono: '{}'",
        "wiki_select": "📖 Szukaj",
        "mining_title": "⛏️ Górnictwo", "mining_skill_label": "Skill", "mining_res_break": "Złamanie", "mining_res_min": "Minerały", "mining_res_frag": "Fragmenty",
        "tools_select": "🛠️ Narzędzia", "btn_party": "🤝 Party", "btn_ss": "💾 Server Save", "btn_mining": "⛏️ Górnictwo",
        "party_title": "Party Share", "party_label": "Level", "party_res": "Level {}:",
        "ss_msg": "⏳ **{}** do zapisu.", "ss_title": "Server Save",
        "cats": { "relics": "💎 Relikty", "runes": "✨ Runy", "tools": "⛏️ Narzędzia", "fishing": "🎣 Wędkarstwo", "ammo": "📦 Amunicja" },
        "rashid_title": "🕌 Rashid jest w: {}", "rashid_desc": "📍 {}", "rashid_map": "🗺️ Mapa", "rashid_error": "Błąd.",
        "alch_select": "⚗️ Menu", "alch_gold": "💰 Konwersja", "alch_skill_label": "Skill", "alch_needs": "Potrzeba:", "alch_conv_name": "Konwertery", "alch_gold_label": "Gold", "alch_gold_ph": "Np: 10k", "alch_res_gold": "Gold", "alch_chance": "Szansa", "cost": "Koszt",
        "time_est": "⏳ Czas"
    }
}
